application:
  showGitHubLinks: true
  social:
    questionnaireUrl: null
  welcomeBanner:
    showOnFirstStart: false
challenges:
  showSolvedNotifications: false
  showHints: false
hackingInstructor:
  isEnabled: false
